import enum


class PapelUsuario(enum.StrEnum):
    VERTICAL = "VERTICAL"
    MARKETING = "MARKETING"
    LIDERANCA = "LIDERANCA"
    ADMIN = "ADMIN"


class StatusProjeto(enum.StrEnum):
    EM_IDEACAO = "EM_IDEACAO"
    EM_DESENVOLVIMENTO = "EM_DESENVOLVIMENTO"
    AGUARDANDO_PRE_LANCAMENTO = "AGUARDANDO_PRE_LANCAMENTO"
    APROVADO_PARA_LANCAMENTO = "APROVADO_PARA_LANCAMENTO"
    LANCADO = "LANCADO"
    EM_ALERTA = "EM_ALERTA"
    ENCERRADO = "ENCERRADO"


class TipoCheckpoint(enum.StrEnum):
    IDEACAO = "IDEACAO"
    DESENVOLVIMENTO = "DESENVOLVIMENTO"
    PRE_LANCAMENTO = "PRE_LANCAMENTO"


class StatusCheckpoint(enum.StrEnum):
    PENDENTE = "PENDENTE"
    SUGERIDO = "SUGERIDO"
    EM_PREENCHIMENTO = "EM_PREENCHIMENTO"
    CONCLUIDO = "CONCLUIDO"


class ClassificacaoFarol(enum.StrEnum):
    PRIORIDADE_MAXIMA = "PRIORIDADE_MAXIMA"
    VALE_INVESTIR_TEMPO = "VALE_INVESTIR_TEMPO"
    BAIXA_PRIORIDADE = "BAIXA_PRIORIDADE"


class TipoAlerta(enum.StrEnum):
    COMPLIANCE_LEGAL = "COMPLIANCE_LEGAL"
    REPUTACAO_MARCA = "REPUTACAO_MARCA"
    POSSIVEL_DUPLICACAO = "POSSIVEL_DUPLICACAO"
    CUSTO_DESPROPORCIONAL = "CUSTO_DESPROPORCIONAL"
    OUTRO = "OUTRO"


class StatusAlerta(enum.StrEnum):
    ABERTO = "ABERTO"
    EM_ANALISE = "EM_ANALISE"
    RESOLVIDO = "RESOLVIDO"
    DESCARTADO = "DESCARTADO"


class DecisaoHumana(enum.StrEnum):
    SOLICITAR_ADAPTACAO = "SOLICITAR_ADAPTACAO"
    ENCERRAR_PROJETO = "ENCERRAR_PROJETO"
    PERMITIR_CONTINUIDADE = "PERMITIR_CONTINUIDADE"


class AutorMensagem(enum.StrEnum):
    USUARIO = "USUARIO"
    AGENTE = "AGENTE"
    SISTEMA = "SISTEMA"
